
version: 2
jobs:
  ui-tests:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Install yarn
          command: yarn install
      - run:
          name: Build yarn
          command: yarn build
      - store_artifacts:
          path: dist/
workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
