# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# https://circleci.com/docs/2.0/browser-testing/#selenium
version: 2
jobs:
  ui-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install yarn
          command: yarn install
      - run:
          name: Start yarn
          command: yarn start
      - store_artifacts:
          path: dist/
workflows:
  version: 2
  commit:
    jobs:
      - ui-tests
